### ISSUE TITLE
Problems with dark mode

### ISSUE THREAD

**Issue by citrux** [pinecrew/pine-forum#2]
![image](https://user-images.githubusercontent.com/864549/125190902-40588d80-e248-11eb-88d5-3e85958e1fb8.png)

Firefox 89.0.2, dark system theme

**Comment by FreeCX** [comment]
У меня всё норм :)
![image](https://user-images.githubusercontent.com/1357744/125190956-73daee00-e22f-11eb-808d-908e4f255265.png)
